version: '3'
services:
  dbservice:
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mynetwork

  appservie:
    build: ./boot
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/blog_app?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 9090:9090

    networks:
      - mynetwork

networks:
  mynetwork:
