# get the base image from docker hub
FROM ubuntu 

# Maintainer: Who is the creator of this image
MAINTAINER Shiva

# Run the command inside the container to install the required packages
RUN apt update

# Run the commnand to echo the message
CMD ["echo", "This  is my first ubuntu image...!"]

# Build the image using the below command
# docker build -t ubuntu . 